spring:
  application:
    name: ms-config

  cloud:
    config:
      server:
        git:
          clone-on-start: on
          uri: ${MS_CONFIG_SERVER_GIT_URI:https://github.com/Juancazzhr/Pets-Care.git}
          default-label: ${MS_CONFIG_SERVER_GIT_DEFAULT_LABEL:dev}
          refresh-rate: 60
          search-paths:
            - back-end/configs/*
          basedir: ${user.home}/config-repo

server:
  port: ${MS_CONFIG_PORT:8888}