spring:
  application:
    name: ms-appointments
  profiles:
    active: ${MS_APPOINTMENTS_PROFILE_ACTIVE:dev}
  config:
    import: configserver:${MS_APPOINTMENTS_CONFIG_SERVER_URL:http://localhost:8888}
  mail:
    debug: false
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: petscaredh@gmail.com
    password: zoox vpqp fscp ylgp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      protocol: smtp
      test-connection: false
