spring:
  application:
    name: ms-discovery

  profiles:
    active: ${SPRING_PROFILE_ACTIVE:local}

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  environment: ${SPRING_PROFILE_ACTIVE:local}

server:
  port: ${PORT:8761}