spring:
  application:
    name: ms-discovery

eureka:
  instance:
    hostname: ${DISCOVERY_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  environment: ${MS_DISCOVERY_PROFILE_ACTIVE:prod}

server:
  port: ${MS_DISCOVERY_PORT:8761}
