server:
  port: ${MS_GATEWAY_PORT:8080}

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - '*'
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-professionals
          uri: lb://ms-professionals
          predicates:
            - Path=/v1/professionals/**

        - id: ms-users
          uri: lb://ms-users
          predicates:
            - Path=/v1/users/**

        - id: ms-users-roles
          uri: lb://ms-users
          predicates:
            - Path=/v1/roles/**

        - id: ms-services
          uri: lb://ms-services
          predicates:
            - Path=/v1/services/**

        - id: ms-pets
          uri: lb://ms-pets
          predicates:
            - Path=/v1/pets/**

        - id: ms-consults
          uri: lb://ms-consults
          predicates:
            - Path=/v1/consults/**

        - id: ms-clients
          uri: lb://ms-clients
          predicates:
            - Path=/v1/clients/**

        - id: ms-appointments
          uri: lb://ms-appointments
          predicates:
            - Path=/v1/appointments/**

        - id: ms-storage
          uri: lb://ms-storage
          predicates:
            - Path=/v1/storage/**

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${MS_GATEWAY_SERVICE_URL:http://localhost:8761/eureka}

info:
  name: ${spring.application.name}
  description: ${spring.application.name} is a Spring Boot application
  version: 1.0.0
  project: Pets Care - Microservices

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

