spring:
  application:
    name: ms-gateway

  cloud:
    gateway:
      routes:
        - id: ms-professionals
          uri: lb://ms-professionals
          predicates:
            - Path=/v1/professionals/**

        - id: ms-users
          uri: lb://ms-users
          predicates:
            - Path=/v1/users/**

        - id: ms-users-roles
          uri: lb://ms-users
          predicates:
            - Path=/v1/roles/**

        - id: ms-services
          uri: lb://ms-services
          predicates:
            - Path=/v1/services/**

        - id: ms-professionals
          uri: lb://ms-professionals
          predicates:
            - Path=/v1/professionals/**

        - id: ms-pets
          uri: lb://ms-pets
          predicates:
            - Path=/v1/pets/**

eureka:
  instance:
    hostname: localhost
    instance-id: ${random.uuid}-${spring.application.name}-${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: ${MS_GATEWAY_SERVICE_URL:http://localhost:8761/eureka}

info:
  name: ${spring.application.name}
  description: ${spring.application.name} is a Spring Boot application
  version: 1.0.0
  project: Pets Care - Microservices

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: on
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: ${MS_GATEWAY_PORT:8080}
