spring:
  application:
    name: ms-gateway

eureka:
  instance:
    hostname: localhost
    instance-id: ${random.uuid}-${spring.application.name}-${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}

server:
  port: ${GATEWAY_PORT:8080}