spring:
  application:
    name: ms-professionals

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  environment: ${MS_SERVICES_PROFILE_ACTIVE:prod}

server:
  port: ${MS_SERVICES_PORT:0}