spring:
  application:
    name: ms-users

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  environment: ${MS_USERS_PROFILE_ACTIVE:dev}

server:
  port: ${MS_USERS_PORT:0}
