name: Pets Care BackEnd Dev CI

run-name: Build and Push Dev Ms

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - 'dev'
    paths: 
    - 'back-end/**/{Dockerfile,pom.xml,src/**}'
    - '.github/workflows/**'

jobs:
  docker-buildx-push:
    runs-on: ubuntu-latest
    name: Docker buildx and push Images
    environment: Dev
    strategy:
      matrix:
        services: [ms-config, ms-discovery, ms-gateway, ms-users, ms-services, ms-pets]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'dev'
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and Push Images for
        uses: docker/build-push-action@v5
        with:
          context: ./back-end/${{ matrix.services }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/petscare-${{ matrix.services }}:dev
